<?php

namespace LogicBundle\Entity;

/**
 * PosturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosturaRepository extends \Doctrine\ORM\EntityRepository
{
}
