<?php

namespace LogicBundle\Entity;

/**
 * TendenciaEstrategiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TendenciaEstrategiaRepository extends \Doctrine\ORM\EntityRepository {
    
}
