<?php

namespace LogicBundle\Entity;

/**
 * TendenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TendenciaRepository extends \Doctrine\ORM\EntityRepository {
    
}
