imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: fosuser/fos_user.yml }
    - { resource: gedmologgable/gedmo_loggable.yml }
    - { resource: custom/assetic.yml }
    - { resource: custom/guzzle.yml }
    - { resource: custom/knp_snappy.yml }
    - { resource: "@AdminBundle/Resources/config/config.yml" }
    - { resource: "@LogicBundle/Resources/config/config.yml" }
    - { resource: "@ServicesBundle/Resources/config/config.yml" }

parameters:
    rol_organismo_deportivo: ROLE_ORGANISMO_DEPORTIVO
    rol_persona_natural: ROLE_PERSONANATURAL
    rol_deportista: ROLE_DEPORTISTA
    session_max_idle_time: 180000
    api_key_google_maps: AIzaSyBNW479uL3oWSbMctP5JSgQ3aIIIKkNrHw
    email_remitente: %mailer_user%

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        form:
            resources:
                - 'AdminBundle:Form'
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes:
        - 'AdminBundle:Form:fields.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'AdminBundle:OhGoogleMaps:Form/fields.html.twig'
        - 'ITInputMaskBundle:Form:inputMaskFields.html.twig'
    globals:
        kernelRootDir:  %kernel.root_dir%
        configuracion:  %configuracion%
        rol_deportista:     "%rol_deportista%"
        rol_persona_natural: "%rol_persona_natural%"
        rol_organismo_deportivo: %rol_organismo_deportivo%
        api_key_google_maps: "%api_key_google_maps%"
    debug:              "%kernel.debug%"
    strict_variables:   "%kernel.debug%"
        
# Doctrine Configuration
doctrine:
    dbal:
        server_version: 9.4
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
           default:
               dql:
                datetime_functions:
                    date_part: LogicBundle\DQL\DatePartFunction
               naming_strategy: doctrine.orm.naming_strategy.underscore
               naming_strategy: doctrine.orm.naming_strategy.underscore
               auto_mapping: true
               mappings:
#                   ApplicationSonataUserBundle:
#                       type: annotation
#                   LogicBundle:
#                       type: annotation
#                   ITOOAuthServerBundle:
#                       type: annotation
                   gedmo_translatable:
                       type: annotation
                       prefix: Gedmo\Translatable\Entity
                       dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                       alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                       is_bundle: false
                   gedmo_translator:
                       type: annotation
                       prefix: Gedmo\Translator\Entity
                       dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                       alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                       is_bundle: false
                   gedmo_loggable:
                       type: annotation
                       prefix: Gedmo\Loggable\Entity
                       dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                       alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                       is_bundle: false
                   gedmo_tree:
                       type: annotation
                       prefix: Gedmo\Tree\Entity
                       dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                       alias: GedmoTree # (optional) it will default to the name set for the mapping
                       is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    auth_mode: '%mailer_auth_mode%'
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    encryption: '%mailer_encryption%'
    port: '%mailer_port%'
    spool: { type: '%mailer_spool_type%', path: '%mailer_spool_path%' }
    sender_address: '%mailer_from_email%'

oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone 

ivory_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link'] }
