<?php

namespace LogicBundle\Repository;

/**
 * AcademicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicoRepository extends \Doctrine\ORM\EntityRepository
{
}
