<?php

namespace LogicBundle\Repository;

/**
 * ActividadPlanClaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadPlanClaseRepository extends \Doctrine\ORM\EntityRepository
{
}
