<?php

namespace LogicBundle\Repository;

/**
 * ActividadPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
