<?php

namespace LogicBundle\Repository;

/**
 * ActividadFisicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadFisicaRepository extends \Doctrine\ORM\EntityRepository
{
}
