<?php

namespace LogicBundle\Repository;

/**
 * ActividadHorarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadHorarioRepository extends \Doctrine\ORM\EntityRepository
{
}
