<?php

namespace LogicBundle\Repository;

/**
 * AnamnesisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnamnesisRepository extends \Doctrine\ORM\EntityRepository
{
}
