<?php

namespace LogicBundle\Repository;

/**
 * AntecedenteMedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntecedenteMedicoRepository extends \Doctrine\ORM\EntityRepository
{
}
