<?php

namespace LogicBundle\Repository;

/**
 * AntecedenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntecedenteRepository extends \Doctrine\ORM\EntityRepository
{
}
