<?php

namespace LogicBundle\Repository;

/**
 * AntropometriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntropometriaRepository extends \Doctrine\ORM\EntityRepository
{
}
