<?php

namespace LogicBundle\Repository;

/**
 * ApoyaTeamMedellinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApoyaTeamMedellinRepository extends \Doctrine\ORM\EntityRepository
{
}
