<?php

namespace LogicBundle\Repository;

/**
 * ArchivoEscenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoEscenarioRepository extends \Doctrine\ORM\EntityRepository
{
}
