<?php

namespace LogicBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AsistenciaReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsistenciaReservaRepository extends EntityRepository
{
    public function buscarAsistentesReservaHorario($reserva, $fecha) {
        $em = $this->getEntityManager();
        
        $query = $em->getRepository('LogicBundle:AsistenciaReserva')
                ->createQueryBuilder("ar")
                ->innerJoin("ar.reserva", "r")
                ->where('r.id = :reserva')
                ->andWhere('ar.fecha = :fecha');
        
        $query->setParameters([
            "fecha" => $fecha,
            "reserva" => $reserva
        ]);

        return $query->getQuery()->getResult();
    }
    
    public function buscarAsistente($usuario, $reserva, $fecha) {
        $em = $this->getEntityManager();
        
        $query = $em->getRepository('LogicBundle:AsistenciaReserva')
            ->createQueryBuilder("ar")
            ->innerJoin('ar.usuario', 'u')
            ->innerJoin('ar.reserva', 'r')
            ->where('u.id = :usuario')
            ->andWhere('r.id = :reserva')
            ->andWhere('ar.fecha = :fecha')
            ->setParameters([
                'usuario' => $usuario->getId(),
                'reserva' => $reserva->getId(),
                'fecha' => $fecha
            ]);
        
        return $query->getQuery()->getOneOrNullResult();
    }
}
