<?php

namespace LogicBundle\Repository;

/**
 * AsistenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsistenciaRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarAsistente($usuario, $oferta, $fecha) {
        $em = $this->getEntityManager();
        
        $query = $em->getRepository('LogicBundle:Asistencia')
            ->createQueryBuilder("a")
            ->innerJoin('a.usuario', 'u')
            ->innerJoin('a.oferta', 'o')
            ->where('u.id = :usuario')
            ->andWhere('o.id = :oferta')
            ->andWhere('a.fecha = :fecha')
            ->setParameters([
                'usuario' => $usuario->getId(),
                'oferta' => $oferta->getId(),
                'fecha' => $fecha
            ]);
        
        return $query->getQuery()->getOneOrNullResult();
    }
    
    public function buscarAsistentesOfertaHorario($oferta, $fecha) {
        $em = $this->getEntityManager();
        
        $query = $em->getRepository('LogicBundle:Asistencia')
                ->createQueryBuilder("a")
                ->innerJoin("a.oferta", "o")
                ->where('o.id = :oferta')
                ->andWhere('a.fecha = :fecha');
        
        $query->setParameters([
            "fecha" => $fecha,
            "oferta" => $oferta
        ]);

        return $query->getQuery()->getResult();
    }
}
