<?php

namespace LogicBundle\Repository;

/**
 * AyudaErgogenicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AyudaErgogenicaRepository extends \Doctrine\ORM\EntityRepository
{
}
