<?php

namespace LogicBundle\Repository;

/**
 * AyudaLaboratorioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AyudaLaboratorioRepository extends \Doctrine\ORM\EntityRepository
{
}
