<?php

namespace LogicBundle\Repository;

/**
 * BannerSimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerSimRepository extends \Doctrine\ORM\EntityRepository {
    
}
