<?php

namespace LogicBundle\Repository;

/**
 * BarriosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarriosRepository extends \Doctrine\ORM\EntityRepository {
    
}
