<?php

namespace LogicBundle\Repository;

/**
 * CampoExtraUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoExtraUsuarioRepository extends \Doctrine\ORM\EntityRepository {
    
}
