<?php

namespace LogicBundle\Repository;

/**
 * CampoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoAmbientalRepository extends \Doctrine\ORM\EntityRepository {
    
}
