<?php

namespace LogicBundle\Repository;

/**
 * CampoEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
