<?php

namespace LogicBundle\Repository;

/**
 * CampoFormularioEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoFormularioEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
