<?php

namespace LogicBundle\Repository;

/**
 * CarneEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarneEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
