<?php

namespace LogicBundle\Repository;

/**
 * CategoriaSetAndSearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaSetAndSearchRepository extends \Doctrine\ORM\EntityRepository
{
}
