<?php

namespace LogicBundle\Repository;

/**
 * CategoriaDisiplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaDisciplinaRepository extends \Doctrine\ORM\EntityRepository
{
}
