<?php

namespace LogicBundle\Repository;

/**
 * CategoriaInfraestructuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaInfraestructuraRepository extends \Doctrine\ORM\EntityRepository
{
}
