<?php

namespace LogicBundle\Repository;

/**
 * CategoriaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
