<?php

namespace LogicBundle\Repository;

/**
 * CategoriaInfraTipoEscenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaInfraTipoEscenarioRepository extends \Doctrine\ORM\EntityRepository
{
}
