<?php

namespace LogicBundle\Repository;

/**
 * CategoriaDivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaDivisionRepository extends \Doctrine\ORM\EntityRepository
{
}
