<?php

namespace LogicBundle\Repository;

/**
 * CategoriaTestControlFisioterapiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaTestControlFisioterapiaRepository extends \Doctrine\ORM\EntityRepository
{
}
