<?php

namespace LogicBundle\Repository;

/**
 * CategoriaNivelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaNivelRepository extends \Doctrine\ORM\EntityRepository
{
}
