<?php

namespace LogicBundle\Repository;

/**
 * CategoriaSubcategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaSubcategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
