<?php

namespace LogicBundle\Repository;

/**
 * CategoriaEnlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaEnlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
