<?php

namespace LogicBundle\Repository;

/**
 * CategoriaInstitucionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaInstitucionalRepository extends \Doctrine\ORM\EntityRepository
{
}
