<?php

namespace LogicBundle\Repository;

/**
 * CategoriaAmbientalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaAmbientalRepository extends \Doctrine\ORM\EntityRepository
{
}
