<?php

namespace LogicBundle\Repository;

/**
 * CategoriaSentadillaArranqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaSentadillaArranqueRepository extends \Doctrine\ORM\EntityRepository
{
}
