<?php

namespace LogicBundle\Repository;

/**
 * ClasificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
