<?php

namespace LogicBundle\Repository;

/**
 * ClasificacionDeporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificacionDeporteRepository extends \Doctrine\ORM\EntityRepository
{
}
