<?php

namespace LogicBundle\Repository;

/**
 * ClasificacionOrganizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificacionOrganizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
