<?php

namespace LogicBundle\Repository;

/**
 * ClaveObservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaveObservacionRepository extends \Doctrine\ORM\EntityRepository
{
}
