<?php

namespace LogicBundle\Repository;

/**
 * ComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponenteRepository extends \Doctrine\ORM\EntityRepository
{
}