<?php

namespace LogicBundle\Repository;

/**
 * ComunaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComunaRepository extends \Doctrine\ORM\EntityRepository {
    
}
