<?php

namespace LogicBundle\Repository;

/**
 * ConsultaMedicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaMedicaRepository extends \Doctrine\ORM\EntityRepository
{
}
