<?php

namespace LogicBundle\Repository;

/**
 * ConsultaPsicologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaPsicologiaRepository extends \Doctrine\ORM\EntityRepository
{
}
