<?php

namespace LogicBundle\Repository;

/**
 * ConsumoSuplementoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumoSuplementoRepository extends \Doctrine\ORM\EntityRepository
{
}
