<?php

namespace LogicBundle\Repository;

/**
 * ConsultaMedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaMedicoRepository extends \Doctrine\ORM\EntityRepository
{
}
