<?php

namespace LogicBundle\Repository;

/**
 * ConsultaNutricionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaNutricionRepository extends \Doctrine\ORM\EntityRepository
{
}
