<?php

namespace LogicBundle\Repository;

/**
 * ConsultaFisioterapiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaFisioterapiaRepository extends \Doctrine\ORM\EntityRepository
{
}
