<?php

namespace LogicBundle\Repository;

/**
 * ContenidoTemaComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenidoTemaComponenteRepository extends \Doctrine\ORM\EntityRepository
{
}
