<?php

namespace LogicBundle\Repository;

/**
 * ContenidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenidoRepository extends \Doctrine\ORM\EntityRepository
{
}
