<?php

namespace LogicBundle\Repository;

/**
 * ContrareferenciaRecomendacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContrareferenciaRecomendacionRepository extends \Doctrine\ORM\EntityRepository
{
}
