<?php

namespace LogicBundle\Repository;

/**
 * DatoFuncionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatoFuncionalRepository extends \Doctrine\ORM\EntityRepository
{
}
