<?php

namespace LogicBundle\Repository;

/**
 * DescripcionHojaEvolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescripcionHojaEvolucionRepository extends \Doctrine\ORM\EntityRepository
{
}
