<?php

namespace LogicBundle\Repository;

/**
 * DiagnosticoPsicologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosticoPsicologiaRepository extends \Doctrine\ORM\EntityRepository
{
}
