<?php

namespace LogicBundle\Repository;

/**
 * DiagnosticoFisioterapiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosticoFisioterapiaRepository extends \Doctrine\ORM\EntityRepository
{
}
