<?php

namespace LogicBundle\Repository;

/**
 * DiagnosticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosticoRepository extends \Doctrine\ORM\EntityRepository
{
}
