<?php

namespace LogicBundle\Repository;

/**
 * DiagnosticoFichaPsicologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosticoFichaPsicologiaRepository extends \Doctrine\ORM\EntityRepository
{
}
