<?php

namespace LogicBundle\Repository;

/**
 * DiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaReservaRepository extends \Doctrine\ORM\EntityRepository {
    public function buscarProgramacion($dia, $reserva) {
        $em = $this->getEntityManager();

        $query = $em->getRepository('LogicBundle:DiaReserva')
            ->createQueryBuilder("dr")
            ->innerJoin('dr.reserva', 'r')
            ->innerJoin('dr.dia', 'd')
            ->where("d.id = :dia")
            ->andWhere("r.id = :reserva")
            ->setParameters([
                'dia' => $dia,
                'reserva' => $reserva
            ]);

        return $query->getQuery()->getOneOrNullResult();
    }
}