<?php

namespace LogicBundle\Repository;

/**
 * DiscapacidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscapacidadRepository extends \Doctrine\ORM\EntityRepository {
    
}
