<?php

namespace LogicBundle\Repository;

/**
 * DisciplinaPruebaRamaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaPruebaRamaRepository extends \Doctrine\ORM\EntityRepository
{
}
