<?php

namespace LogicBundle\Repository;

/**
 * DisciplinasEscenarioDeportivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinasEscenarioDeportivoRepository extends \Doctrine\ORM\EntityRepository
{
}
