<?php

namespace LogicBundle\Repository;

use Doctrine\ORM\EntityRepository;
use LogicBundle\Entity\Disciplina;
use LogicBundle\Entity\OrganizacionDeportiva;

/**
 * DisciplinaOrganizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaOrganizacionRepository extends EntityRepository {

    public function buscarDisciplinaOrganizacion(OrganizacionDeportiva $OrganizacionDeportiva, Disciplina $disciplina) {
        $em = $this->getEntityManager();

        $query = $em->getRepository('LogicBundle:DisciplinaOrganizacion')
                ->createQueryBuilder("do")
                ->innerJoin("do.organizacion", "o")
                ->innerJoin("do.disciplina", "d")
                ->where('o.id = :organizacion')
                ->andWhere('d.id = :disciplina');

        $query->setParameters([
            "organizacion" => $OrganizacionDeportiva,
            "disciplina" => $disciplina
        ]);

        return $query->getQuery()->getOneOrNullResult();
    }

}
