<?php

namespace LogicBundle\Repository;

/**
 * DisciplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaRepository extends \Doctrine\ORM\EntityRepository {
    
}
