<?php

namespace LogicBundle\Repository;

/**
 * DisciplinaEstrategiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaEstrategiaRepository extends \Doctrine\ORM\EntityRepository {
    
}
