<?php

namespace LogicBundle\Repository;

/**
 * DivisionBloqueoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DivisionBloqueoRepository extends \Doctrine\ORM\EntityRepository
{
}
