<?php

namespace LogicBundle\Repository;

/**
 * DivisionReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DivisionReservaRepository extends \Doctrine\ORM\EntityRepository
{
}
