<?php

namespace LogicBundle\Repository;

/**
 * DocumentosOrganismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentosOrganismoRepository extends \Doctrine\ORM\EntityRepository {
    
}
