<?php

namespace LogicBundle\Repository;

/**
 * EncuentroSistemaDosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuentroSistemaDosRepository extends \Doctrine\ORM\EntityRepository
{
}
