<?php

namespace LogicBundle\Repository;

/**
 * EncuestaPeriodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestaPeriodoRepository extends \Doctrine\ORM\EntityRepository
{
}
