<?php

namespace LogicBundle\Repository;

/**
 * EncuentroSistemaCuatroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuentroSistemaCuatroRepository extends \Doctrine\ORM\EntityRepository
{
}
