<?php

namespace LogicBundle\Repository;

/**
 * EncuentroSistemaLigaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuentroSistemaLigaRepository extends \Doctrine\ORM\EntityRepository
{
}
