<?php

namespace LogicBundle\Repository;


use Doctrine\ORM\EntityRepository;

use Entities;


/**
 * EncuentrosSistemaTresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuentroSistemaTresRepository extends \Doctrine\ORM\EntityRepository
{
}
