<?php

namespace LogicBundle\Repository;

/**
 * EncuestaOpcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestaOpcionRepository extends \Doctrine\ORM\EntityRepository
{
}
