<?php

namespace LogicBundle\Repository;

/**
 * EncuestaRespuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestaRespuestaRepository extends \Doctrine\ORM\EntityRepository
{
}
