<?php

namespace LogicBundle\Repository;

/**
 * EncuestaPreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestaPreguntaRepository extends \Doctrine\ORM\EntityRepository
{
}
