<?php

namespace LogicBundle\Repository;

/**
 * EnfoqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfoqueRepository extends \Doctrine\ORM\EntityRepository
{
}
