<?php

namespace LogicBundle\Repository;

/**
 * EnlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
