<?php

namespace LogicBundle\Repository;

/**
 * EntrevistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrevistaRepository extends \Doctrine\ORM\EntityRepository
{
}
