<?php

namespace LogicBundle\Repository;

/**
 * EquipoEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
