<?php

namespace LogicBundle\Repository;

/**
 * ErgogenicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErgogenicaRepository extends \Doctrine\ORM\EntityRepository
{
}
