<?php

namespace LogicBundle\Repository;

/**
 * EscenarioCategoriaAmbientalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscenarioCategoriaAmbientalRepository extends \Doctrine\ORM\EntityRepository
{
}
