<?php

namespace LogicBundle\Repository;

/**
 * EscenarioCategoriaSubCategoriaInfraestructuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscenarioCategoriaSubCategoriaInfraestructuraRepository extends \Doctrine\ORM\EntityRepository
{
}
