<?php

namespace LogicBundle\Repository;

/**
 * EscenarioCategoriaInfraestructuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscenarioCategoriaInfraestructuraRepository extends \Doctrine\ORM\EntityRepository
{
}
