<?php

namespace LogicBundle\Repository;

/**
 * EscenarioCategoriaSubCategoriaInfraestructura
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscenarioCategoriaSubCategoriaInfraestructuraRespository extends \Doctrine\ORM\EntityRepository
{
}
