<?php

namespace LogicBundle\Repository;

/**
 * EscenarioDeportivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscenarioDeportivoRepository extends \Doctrine\ORM\EntityRepository {
    
}
