<?php

namespace LogicBundle\Repository;

/**
 * EscenarioSubCategoriaCampoRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscenarioSubCategoriaInfraestructuraCampoRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarValorAlmacenado($escenarioSubCategoria, $campo, $subCategoria) {
        $em = $this->getEntityManager();
        
        $query = $em->getRepository('LogicBundle:EscenarioSubCategoriaInfraestructuraCampo')
            ->createQueryBuilder("esic")
            ->innerJoin('esic.campoInfraestructura', 'ci')
            ->innerJoin('esic.escenarioCategoriaSubCategoria', 'es')
            ->innerJoin('es.subcategoriaInfraestructura', 'sci')
            ->where('ci.id = :campo')
            ->andWhere('es.id = :escenarioSubCategoria')
            ->andWhere('sci.id = :subCategoria')
            ->setParameters([
                'campo' => $campo,
                'escenarioSubCategoria' => $escenarioSubCategoria,
                'subCategoria' => $subCategoria
            ]);
        
        return $query->getQuery()->getOneOrNullResult();
    }
}
