<?php

namespace LogicBundle\Repository;

/**
 * EscenarioSubCategoriaAmbientalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscenarioSubCategoriaAmbientalRepository extends \Doctrine\ORM\EntityRepository
{
}
