<?php

namespace LogicBundle\Repository;

/**
 * EscenarioSubCategoriaAmbientalCampoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscenarioSubCategoriaAmbientalCampoRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarValorAlmacenado($escenarioSubCategoria, $campo, $subCategoria) {
        $em = $this->getEntityManager();
        
        $query = $em->getRepository('LogicBundle:EscenarioSubCategoriaAmbientalCampo')
            ->createQueryBuilder("esac")
            ->innerJoin('esac.campoAmbiental', 'ca')
            ->innerJoin('esac.escenarioSubCategoriaAmbiental', 'es')
            ->innerJoin('es.subcategoriaAmbiental', 'sca')
            ->where('ca.id = :campo')
            ->andWhere('es.id = :escenarioSubCategoria')
            ->andWhere('sca.id = :subCategoria')
            ->setParameters([
                'campo' => $campo,
                'escenarioSubCategoria' => $escenarioSubCategoria,
                'subCategoria' => $subCategoria
            ]);
        
        return $query->getQuery()->getOneOrNullResult();
    }
}
