<?php

namespace LogicBundle\Repository;

/**
 * EstablecimientoEducativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablecimientoEducativoRepository extends \Doctrine\ORM\EntityRepository {
    
}
