<?php

namespace LogicBundle\Repository;

/**
 * EstratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstratoRepository extends \Doctrine\ORM\EntityRepository {
    
}
