<?php

namespace LogicBundle\Repository;

/**
 * EstrategiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstrategiaRepository extends \Doctrine\ORM\EntityRepository {
    
}
