<?php

namespace LogicBundle\Repository;

use Doctrine\ORM\EntityRepository;
use LogicBundle\Entity\CampoUsuario;
use LogicBundle\Entity\Estrategia;

/**
 * EstrategiaCampoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstrategiaCampoRepository extends EntityRepository
{
    public function busacrCampo(Estrategia $estrategia, CampoUsuario $campo) {
        $em = $this->getEntityManager();
        
        $query = $em->getRepository('LogicBundle:EstrategiaCampo')
            ->createQueryBuilder("ec")
            ->innerJoin('ec.campoUsuario', 'cu')
            ->innerJoin('ec.estrategia', 'e')
            ->where('e.id = :estrategia')
            ->andWhere('cu.id = :campoUsuario')
            ->setParameters([
                'estrategia' => $estrategia->getId(),
                'campoUsuario' => $campo->getId()
            ]);
        
        return $query->getQuery()->getOneOrNullResult();
    }
}
