<?php

namespace LogicBundle\Repository;

/**
 * EtniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtniaRepository extends \Doctrine\ORM\EntityRepository
{
}
