<?php

namespace LogicBundle\Repository;

/**
 * EvaluacionPosicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionPosicionRepository extends \Doctrine\ORM\EntityRepository
{
}
