<?php

namespace LogicBundle\Repository;

/**
 * EventoRolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRolRepository extends \Doctrine\ORM\EntityRepository
{
}
