<?php

namespace LogicBundle\Repository;

/**
 * ExamenFisicoMedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenFisicoMedicoRepository extends \Doctrine\ORM\EntityRepository
{
}
