<?php

namespace LogicBundle\Repository;

/**
 * ExamenFisicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenFisicoRepository extends \Doctrine\ORM\EntityRepository
{
}
