<?php

namespace LogicBundle\Repository;

/**
 * FactorExternoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactorExternoRepository extends \Doctrine\ORM\EntityRepository
{
}
