<?php

namespace LogicBundle\Repository;

/**
 * FaltasEncuentroSistemaDosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaltasEncuentroSistemaDosRepository extends \Doctrine\ORM\EntityRepository
{
}
