<?php

namespace LogicBundle\Repository;

/**
 * FaltasEncuentroJugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaltasEncuentroJugadorRepository extends \Doctrine\ORM\EntityRepository
{
}
