<?php

namespace LogicBundle\Repository;

/**
 * FamiliarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamiliarRepository extends \Doctrine\ORM\EntityRepository
{
}
