<?php

namespace LogicBundle\Repository;

/**
 * FaseComponentePrincipioSubPrincipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaseComponentePrincipioSubPrincipioRepository extends \Doctrine\ORM\EntityRepository
{
}
