<?php

namespace LogicBundle\Repository;

/**
 * FaseEntrenamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaseEntrenamientoRepository extends \Doctrine\ORM\EntityRepository
{
}
