<?php

namespace LogicBundle\Repository;

/**
 * FaseComponentePrincipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaseComponentePrincipioRepository extends \Doctrine\ORM\EntityRepository
{
}
