<?php

namespace LogicBundle\Repository;

/**
 * FichaCampoPsicologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichaCampoPsicologiaRepository extends \Doctrine\ORM\EntityRepository
{
}
