<?php

namespace LogicBundle\Repository;

/**
 * FichaCampoFisioterapiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichaCampoFisioterapiaRepository extends \Doctrine\ORM\EntityRepository
{
}
