<?php

namespace LogicBundle\Repository;

/**
 * FichaCampoNutricionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichaCampoNutricionRepository extends \Doctrine\ORM\EntityRepository
{
}
