<?php

namespace LogicBundle\Repository;

/**
 * FuenteFinanciacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuenteFinanciacionRepository extends \Doctrine\ORM\EntityRepository {
    
}
