<?php

namespace LogicBundle\Repository;

/**
 * GaleriaDeportistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaDeportistaRepository extends \Doctrine\ORM\EntityRepository
{
}
