<?php

namespace LogicBundle\Repository;

/**
 * GruposEncuentroSistemaCuatroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruposEncuentroSistemaCuatroRepository extends \Doctrine\ORM\EntityRepository
{
}
