<?php

namespace LogicBundle\Repository;

/**
 * HabitacionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabitacionalRepository extends \Doctrine\ORM\EntityRepository
{
}
