<?php

namespace LogicBundle\Repository;

/**
 * HojaEvolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HojaEvolucionRepository extends \Doctrine\ORM\EntityRepository
{
}
