<?php

namespace LogicBundle\Repository;

/**
 * ImagenesNoticiasTeamMedellinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenesNoticiasTeamMedellinRepository extends \Doctrine\ORM\EntityRepository
{
}
