<?php

namespace LogicBundle\Repository;

/**
 * IndicadorLogroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicadorLogroRepository extends \Doctrine\ORM\EntityRepository
{
}
