<?php

namespace LogicBundle\Repository;

/**
 * InformacionExtraUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformacionExtraUsuarioRepository extends \Doctrine\ORM\EntityRepository {
    
}
