<?php

namespace LogicBundle\Repository;

/**
 * InstitucionalEstrategiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitucionalEstrategiaRepository extends \Doctrine\ORM\EntityRepository
{
}
