<?php

namespace LogicBundle\Repository;

/**
 * JugadorEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadorEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
