<?php

namespace LogicBundle\Repository;

/**
 * KitTerritorialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KitTerritorialRepository extends \Doctrine\ORM\EntityRepository
{
}
