<?php

namespace LogicBundle\Repository;

/**
 * KitTerritorialComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KitTerritorialComponenteRepository extends \Doctrine\ORM\EntityRepository
{
}
