<?php

namespace LogicBundle\Repository;

/**
 * LaboratorioHojaEvolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratorioHojaEvolucionRepository extends \Doctrine\ORM\EntityRepository
{
}
