<?php

namespace LogicBundle\Repository;

/**
 * LaboratorioMedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratorioMedicoRepository extends \Doctrine\ORM\EntityRepository
{
}
