<?php

namespace LogicBundle\Repository;

/**
 * MedicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicionRepository extends \Doctrine\ORM\EntityRepository
{
}
