<?php

namespace LogicBundle\Repository;

/**
 * MotivoCancelacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivoCancelacionRepository extends \Doctrine\ORM\EntityRepository
{
}
