<?php

namespace LogicBundle\Repository;

/**
 * MultimediaDeportistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultimediaDeportistaRepository extends \Doctrine\ORM\EntityRepository
{
}
