<?php

namespace LogicBundle\Repository;

/**
 * MunicipiosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipiosRepository extends \Doctrine\ORM\EntityRepository {
    
}
