<?php

namespace LogicBundle\Repository;

/**
 * NivelObjetivoActividadEspecificaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelObjetivoActividadEspecificaRepository extends \Doctrine\ORM\EntityRepository
{
}
