<?php

namespace LogicBundle\Repository;

/**
 * NivelSubPrincipioObjetivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelSubPrincipioObjetivoRepository extends \Doctrine\ORM\EntityRepository
{
}
