<?php

namespace LogicBundle\Repository;

/**
 * NivelPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
