<?php

namespace LogicBundle\Repository;

/**
 * NivelPlanMetodologicoSubPrincipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelPlanMetodologicoSubPrincipioRepository extends \Doctrine\ORM\EntityRepository
{
}
