<?php

namespace LogicBundle\Repository;

/**
 * NivelComponenteContenidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelComponenteContenidoRepository extends \Doctrine\ORM\EntityRepository
{
}
