<?php

namespace LogicBundle\Repository;

/**
 * NivelIndependenciaFuncionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelIndependenciaFuncionalRepository extends \Doctrine\ORM\EntityRepository
{
}
