<?php

namespace LogicBundle\Repository;

/**
 * NivelEscolaridadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelEscolaridadRepository extends \Doctrine\ORM\EntityRepository {
    
}
