<?php

namespace LogicBundle\Repository;

/**
 * NivelFaseComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelFaseComponenteRepository extends \Doctrine\ORM\EntityRepository
{
}
