<?php

namespace LogicBundle\Repository;

/**
 * NotaNutricionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaNutricionRepository extends \Doctrine\ORM\EntityRepository
{
}
