<?php

namespace LogicBundle\Repository;

/**
 * NotaPsicologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaPsicologiaRepository extends \Doctrine\ORM\EntityRepository
{
}
