<?php

namespace LogicBundle\Repository;

/**
 * NotaAclaratoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaAclaratoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
