<?php

namespace LogicBundle\Repository;

/**
 * NotaFisioterapiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaFisioterapiaRepository extends \Doctrine\ORM\EntityRepository
{
}
