<?php

namespace LogicBundle\Repository;

/**
 * NoticiasTeamMedellinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiasTeamMedellinRepository extends \Doctrine\ORM\EntityRepository
{
}
