<?php

namespace LogicBundle\Repository;

/**
 * NoticiaTeamMedellinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaTeamMedellinRepository extends \Doctrine\ORM\EntityRepository
{
}
