<?php

namespace LogicBundle\Repository;

/**
 * ObservacionEspecialidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacionEspecialidadRepository extends \Doctrine\ORM\EntityRepository
{
}
