<?php

namespace LogicBundle\Repository;

/**
 * OcupacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OcupacionRepository extends \Doctrine\ORM\EntityRepository {
    
}
