<?php

namespace LogicBundle\Repository;

/**
 * OfertaDivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaDivisionRepository extends \Doctrine\ORM\EntityRepository
{
}
