<?php

namespace LogicBundle\Repository;

/**
 * OpcionCampoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpcionCampoRepository extends \Doctrine\ORM\EntityRepository
{
}
