<?php

namespace LogicBundle\Repository;

/**
 * OrganismoDeportistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismoDeportistaRepository extends \Doctrine\ORM\EntityRepository {
    
}
