<?php

namespace LogicBundle\Repository;

/**
 * OrganoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganoRepository extends \Doctrine\ORM\EntityRepository {
    
}
