<?php

namespace LogicBundle\Repository;

use Application\Sonata\UserBundle\Entity\User;

/**
 * OrganizacionDeportivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionDeportivaRepository extends \Doctrine\ORM\EntityRepository {

    public function buscarOrganizacionesDeportivas(User $usuario, $id = null) {
        $em = $this->getEntityManager();

        $query = $em->getRepository("LogicBundle:OrganizacionDeportiva")
                ->createQueryBuilder("od")
                ->innerJoin("od.usuarios", "u")
                ->where("u.id = :usuario")
                ->setParameter("usuario", $usuario->getId());

        if ($id) {
            $query->andWhere("od.id = :id")
                    ->setParameter("id", $id);

            return $query->getQuery()->getOneOrNullResult();
        }

        return $query;
    }

    public function buscarOrganizacionDeportista($organizacionDeportiva, $usuario) {
        $em = $this->getEntityManager();
        $query = $em->getRepository('LogicBundle:OrganizacionDeportiva')
                ->createQueryBuilder("od")
                ->innerJoin('od.disciplinaOrganizaciones', 'do')
                ->innerJoin('do.deportistas', 'd')
                ->innerJoin('d.usuarioDeportista', 'ud')
                ->where('ud.id = :usuario')
                ->setMaxResults(1)
                ->setParameters([
            'usuario' => $usuario,
        ]);
        return $query->getQuery()->getOneOrNullResult();
    }

}
