<?php

namespace LogicBundle\Repository;

/**
 * OrientacionSexualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrientacionSexualRepository extends \Doctrine\ORM\EntityRepository {
    
}
