<?php

namespace LogicBundle\Repository;

/**
 * ParentezcoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentezcoRepository extends \Doctrine\ORM\EntityRepository
{
}
