<?php

namespace LogicBundle\Repository;

/**
 * PatrocinadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatrocinadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
