<?php

namespace LogicBundle\Repository;

/**
 * PerfilOrganismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilOrganismoRepository extends \Doctrine\ORM\EntityRepository {
    
}
