<?php

namespace LogicBundle\Repository;

/**
 * PerfilCuerpoTecnicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilCuerpoTecnicoRepository extends \Doctrine\ORM\EntityRepository
{
}
