<?php

namespace LogicBundle\Repository;

/**
 * pivoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pivoteRepository extends \Doctrine\ORM\EntityRepository
{
}
