<?php

namespace LogicBundle\Repository;

/**
 * PlanMetodologicoActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanMetodologicoActividadRepository extends \Doctrine\ORM\EntityRepository
{
}
