<?php

namespace LogicBundle\Repository;

/**
 * PlanMetodologicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanMetodologicoRepository extends \Doctrine\ORM\EntityRepository
{
}
