<?php

namespace LogicBundle\Repository;

/**
 * PlanClaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanClaseRepository extends \Doctrine\ORM\EntityRepository
{

    public function queryEstrategia($planClase) {
        $query = $this->createQueryBuilder('e')
            ->join('e.ofertas', 'o')
            ->join('o.planAnualMetodologico', 'pam')
            ->join('pam.componentes', 'com')
            ->join('com.contenidos', 'con')
            ->join('con.actividades', 'a')
            ->join('a.planesClase', 'ap')
            ->join('ap.planClase', 'pc')
            ->where('pc.id = :id_plan_clase')
            ->setParameter('id_plan_clase', $planClase->getId());
    
        return $query;
    }

    public function findEstrategia($planClase){
        return $this->queryEstrategia($planClase)
                    ->getQuery()
                    ->getResult();
    }

}
