<?php

namespace LogicBundle\Repository;

/**
 * PlanIntervencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanIntervencionRepository extends \Doctrine\ORM\EntityRepository
{
}
