<?php

namespace LogicBundle\Repository;

/**
 * PlanAnualMetodologicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanAnualMetodologicoRepository extends \Doctrine\ORM\EntityRepository
{
}
