<?php

namespace LogicBundle\Repository;

/**
 * PrecedenciaDeportivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecedenciaDeportivaRepository extends \Doctrine\ORM\EntityRepository
{
}
