<?php

namespace LogicBundle\Repository;

/**
 * PresenciaDolorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresenciaDolorRepository extends \Doctrine\ORM\EntityRepository
{
}
