<?php

namespace LogicBundle\Repository;

/**
 * PrincipioPlanMetodologicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrincipioPlanMetodologicoRepository extends \Doctrine\ORM\EntityRepository
{
}
