<?php

namespace LogicBundle\Repository;

/**
 * ProgramacionReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramacionReservaRepository extends \Doctrine\ORM\EntityRepository {
    public function buscarProgramacion($dia, $reserva){
        $em = $this->getEntityManager();
        $query = $em->getRepository('LogicBundle:ProgramacionReserva')
            ->createQueryBuilder("pr")
            ->where("pr.dia = :dia")
            ->andWhere("pr.reserva = :reserva")
            ->setParameters([
                'dia' => $dia,
                'reserva' => $reserva
            ]);

        return $query->getQuery()->getOneOrNullResult();
    }
}
