<?php

namespace LogicBundle\Repository;

/**
 * PruebaSentadillaArranqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PruebaSentadillaArranqueRepository extends \Doctrine\ORM\EntityRepository
{
}
