<?php

namespace LogicBundle\Repository;

/**
 * PruebaPosturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PruebaPosturaRepository extends \Doctrine\ORM\EntityRepository
{
}
