<?php

namespace LogicBundle\Repository;

/**
 * PruebaControlFisioterapiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PruebaControlFisioterapiaRepository extends \Doctrine\ORM\EntityRepository
{
}
