<?php

namespace LogicBundle\Repository;

/**
 * PruebaSetAndSearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PruebaSetAndSearchRepository extends \Doctrine\ORM\EntityRepository
{
}
