<?php

namespace LogicBundle\Repository;

/**
 * PruebaLumboPelvicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PruebaLumboPelvicaRepository extends \Doctrine\ORM\EntityRepository
{
}
