<?php

namespace LogicBundle\Repository;

/**
 * PruebaEstabilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PruebaEstabilidadRepository extends \Doctrine\ORM\EntityRepository
{
}
