<?php

namespace LogicBundle\Repository;

use LogicBundle\Entity\PuntoAtencion;
use Doctrine\ORM\EntityRepository;

/**
 * PuntoAtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntoAtencionRepository extends EntityRepository {

    public function consultaDireccionBarrio($direccion, $barrio) {
        $em = $this->getEntityManager();

        $qb = $em->getRepository(PuntoAtencion::class)
                ->createQueryBuilder('p');
        $qb->where('p.barrio = ' . $barrio->getId());
        if ($direccion) {

            $qb->AndWhere('p.direccion like :direccion')
                    ->setParameter('direccion', '%' . $direccion . '%');
        }
        $qb
                ->orderBy('p.direccion', 'ASC');

        return $qb->getQuery()->getResult();
    }

}
