<?php

namespace LogicBundle\Repository;

/**
 * PuntuacionPruebaLumboPelvicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntuacionPruebaLumboPelvicaRepository extends \Doctrine\ORM\EntityRepository
{
}
