<?php

namespace LogicBundle\Repository;

/**
 * PuntuacionSentadillaArranqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntuacionSentadillaArranqueRepository extends \Doctrine\ORM\EntityRepository
{
}
