<?php

namespace LogicBundle\Repository;

/**
 * PuntuacionSetAndSearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntuacionSetAndSearchRepository extends \Doctrine\ORM\EntityRepository
{
}
