<?php

namespace LogicBundle\Repository;

/**
 * RecordatorioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordatorioRepository extends \Doctrine\ORM\EntityRepository
{
}
