<?php

namespace LogicBundle\Repository;

/**
 * RecomendadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecomendadoRepository extends \Doctrine\ORM\EntityRepository
{
}
