<?php

namespace LogicBundle\Repository;

/**
 * RecordatorioComidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordatorioComidaRepository extends \Doctrine\ORM\EntityRepository
{
}
