<?php

namespace LogicBundle\Repository;

/**
 * RegistroParaclinicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroParaclinicoRepository extends \Doctrine\ORM\EntityRepository
{
}
