<?php

namespace LogicBundle\Repository;

/**
 * RemisionHojaEvolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemisionHojaEvolucionRepository extends \Doctrine\ORM\EntityRepository
{
}
