<?php

namespace LogicBundle\Repository;

/**
 * RemisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemisionRepository extends \Doctrine\ORM\EntityRepository
{
}
