<?php

namespace LogicBundle\Repository;

/**
 * RemisionMedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemisionMedicoRepository extends \Doctrine\ORM\EntityRepository
{
}
