<?php

namespace LogicBundle\Repository;

/**
 * ReservaUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
