<?php

namespace LogicBundle\Repository;

/**
 * ResponsableTareaActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableTareaActividadRepository extends \Doctrine\ORM\EntityRepository
{
}
