<?php

namespace LogicBundle\Repository;

/**
 * RespuestaFuncionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespuestaFuncionalRepository extends \Doctrine\ORM\EntityRepository
{
}
