<?php

namespace LogicBundle\Repository;

/**
 * RestriccionDisciplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestriccionDisciplinaRepository extends \Doctrine\ORM\EntityRepository
{
}
