<?php

namespace LogicBundle\Repository;

/**
 * ResultadosEncuentrosSistemaDosVoleibolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadosEncuentrosSistemaDosVoleibolRepository extends \Doctrine\ORM\EntityRepository
{
}
