<?php

namespace LogicBundle\Repository;

/**
 * ResultadoEncuentroSistemaLigaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoEncuentroSistemaLigaRepository extends \Doctrine\ORM\EntityRepository
{
}
