<?php

namespace LogicBundle\Repository;

/**
 * ResultadosEncuentroSistemaCuatroVoleibolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadosEncuentroSistemaCuatroVoleibolRepository extends \Doctrine\ORM\EntityRepository
{
}
