<?php

namespace LogicBundle\Repository;

/**
 * ResultadoDeportistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoDeportistaRepository extends \Doctrine\ORM\EntityRepository
{
}
