<?php

namespace LogicBundle\Repository;

/**
 * ResultadosEncuentroSistemaCuatroOtrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadosEncuentroSistemaCuatroOtrosRepository extends \Doctrine\ORM\EntityRepository
{
}
