<?php

namespace LogicBundle\Repository;

/**
 * ResultadosEncuentroSistemaDosOtrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadosEncuentroSistemaDosOtrosRepository extends \Doctrine\ORM\EntityRepository
{
}
