<?php

namespace LogicBundle\Repository;

/**
 * SancionEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SancionEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
