<?php

namespace LogicBundle\Repository;

/**
 * SancionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SancionRepository extends \Doctrine\ORM\EntityRepository
{
}
