<?php

namespace LogicBundle\Repository;

/**
 * SegmentacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegmentacionRepository extends \Doctrine\ORM\EntityRepository
{
}
