<?php

namespace LogicBundle\Repository;

/**
 * SentadillaArranqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentadillaArranqueRepository extends \Doctrine\ORM\EntityRepository
{
}
