<?php

namespace LogicBundle\Repository;

/**
 * ServicioPublicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioPublicoRepository extends \Doctrine\ORM\EntityRepository
{
}
