<?php

namespace LogicBundle\Repository;

/**
 * SetAndSearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetAndSearchRepository extends \Doctrine\ORM\EntityRepository
{
}
