<?php

namespace LogicBundle\Repository;

/**
 * SistemaJuegoCuatroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SistemaJuegoCuatroRepository extends \Doctrine\ORM\EntityRepository
{
}
