<?php

namespace LogicBundle\Repository;

/**
 * SistemaJuegoDosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SistemaJuegoDosRepository extends \Doctrine\ORM\EntityRepository
{
}
