<?php

namespace LogicBundle\Repository;

/**
 * SistemaJuegoLigaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SistemaJuegoLigaRepository extends \Doctrine\ORM\EntityRepository
{
}
