<?php

namespace LogicBundle\Repository;

/**
 * SistemaJuegoUnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SistemaJuegoUnoRepository extends \Doctrine\ORM\EntityRepository
{
}
