<?php

namespace LogicBundle\Repository;

/**
 * SubcategoriaInfraestructuraEscenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoriaInfraestructuraEscenarioRepository extends \Doctrine\ORM\EntityRepository
{
}
