<?php

namespace LogicBundle\Repository;

/**
 * SubCategoriaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoriaEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
