<?php

namespace LogicBundle\Repository;

/**
 * SubcategoriaAmbientalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoriaAmbientalRepository extends \Doctrine\ORM\EntityRepository
{
}
