<?php

namespace LogicBundle\Repository;

/**
 * SubcategoriaInfraestructuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoriaInfraestructuraRepository extends \Doctrine\ORM\EntityRepository
{
}
