<?php

namespace LogicBundle\Repository;

/**
 * SubcategoriaAmbientalEscenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoriaAmbientalEscenarioRepository extends \Doctrine\ORM\EntityRepository
{
}
