<?php

namespace LogicBundle\Repository;

/**
 * SubDiscapacidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubDiscapacidadRepository extends \Doctrine\ORM\EntityRepository {
    
}
