<?php

namespace LogicBundle\Repository;

/**
 * SubNivelPlanMetodologicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubNivelPlanMetodologicoRepository extends \Doctrine\ORM\EntityRepository
{
}
