<?php

namespace LogicBundle\Repository;

/**
 * SubPrincipioPlanMetodologicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubPrincipioPlanMetodologicoRepository extends \Doctrine\ORM\EntityRepository
{
}
