<?php

namespace LogicBundle\Repository;

/**
 * TareaActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareaActividadRepository extends \Doctrine\ORM\EntityRepository
{
}
