<?php

namespace LogicBundle\Repository;

/**
 * TemaPorComunaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaPorComunaRepository extends \Doctrine\ORM\EntityRepository
{
}
