<?php

namespace LogicBundle\Repository;

/**
 * TemaComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaComponenteRepository extends \Doctrine\ORM\EntityRepository
{
}
