<?php

namespace LogicBundle\Repository;

/**
 * TemaModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaModeloRepository extends \Doctrine\ORM\EntityRepository
{
}
