<?php

namespace LogicBundle\Repository;

/**
 * TemaComunaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaComunaRepository extends \Doctrine\ORM\EntityRepository
{
}
