<?php

namespace LogicBundle\Repository;

/**
 * TendenciaEscenarioDeportivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TendenciaEscenarioDeportivoRepository extends \Doctrine\ORM\EntityRepository
{
}
