<?php

namespace LogicBundle\Repository;

/**
 * TerminoCondicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminoCondicionRepository extends \Doctrine\ORM\EntityRepository
{
}
