<?php

namespace LogicBundle\Repository;

/**
 * TestControlFisioterapiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestControlFisioterapiaRepository extends \Doctrine\ORM\EntityRepository
{
}
