<?php

namespace LogicBundle\Repository;

/**
 * TestPracticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestPracticoRepository extends \Doctrine\ORM\EntityRepository
{
}
