<?php

namespace LogicBundle\Repository;

/**
 * TimpoComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimpoComponenteRepository extends \Doctrine\ORM\EntityRepository
{
}
