<?php

namespace LogicBundle\Repository;

/**
 * TipoReservaEscenarioDeportivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoReservaEscenarioDeportivoRepository extends \Doctrine\ORM\EntityRepository
{
}
