<?php

namespace LogicBundle\Repository;

/**
 * TipoEscenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEscenarioRepository extends \Doctrine\ORM\EntityRepository {
    
}
