<?php

namespace LogicBundle\Repository;

/**
 * TipoEstablecimientoEducativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEstablecimientoEducativoRepository extends \Doctrine\ORM\EntityRepository {
    
}
