<?php

namespace LogicBundle\Repository;

/**
 * TipoTareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTareaRepository extends \Doctrine\ORM\EntityRepository
{
}
