<?php

namespace LogicBundle\Repository;

/**
 * TipoEnfoqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEnfoqueRepository extends \Doctrine\ORM\EntityRepository
{
}
