<?php

namespace LogicBundle\Repository;

/**
 * TipoReservaEscenarioDeportivoDivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoReservaEscenarioDeportivoDivisionRepository extends \Doctrine\ORM\EntityRepository
{
}
