<?php

namespace LogicBundle\Repository;

/**
 * TipoFaltaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoFaltaRepository extends \Doctrine\ORM\EntityRepository
{
}
