<?php

namespace LogicBundle\Repository;

/**
 * TipoDiagnosticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDiagnosticoRepository extends \Doctrine\ORM\EntityRepository
{
}
