<?php

namespace LogicBundle\Repository;

/**
 * TipoTiempoEjecucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTiempoEjecucionRepository extends \Doctrine\ORM\EntityRepository
{
}
