<?php

namespace LogicBundle\Repository;

/**
 * TipoSangreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoSangreRepository extends \Doctrine\ORM\EntityRepository {
    
}
