<?php

namespace LogicBundle\Repository;

use LogicBundle\Entity\TipoOrganismo;
use Doctrine\ORM\EntityRepository;
/**
 * TipoOrganismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoOrganismoRepository extends EntityRepository {
    
    public function findAllArray() {
        $organismos = $this->findAll([], ['nombre' => 'ASC']);
        $tipos = array();
        $organismo = new TipoOrganismo();

        foreach ($organismos as $organismo) {
            $tipos[] = array(
                'id' => $organismo->getId(),
                'nombre' => $organismo->getNombre(),
            );
}
        return $tipos;
    }

}
