<?php

namespace LogicBundle\Repository;

/**
 * TipoReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoReservaRepository extends \Doctrine\ORM\EntityRepository
{
}
