<?php

namespace LogicBundle\Repository;

/**
 * TipoDireccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDireccionRepository extends \Doctrine\ORM\EntityRepository
{
}
