<?php

namespace LogicBundle\Repository;

/**
 * TipoIdentificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoIdentificacionRepository extends \Doctrine\ORM\EntityRepository {
    
}
