<?php

namespace LogicBundle\Repository;

/**
 * TipoDesplazadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDesplazadoRepository extends \Doctrine\ORM\EntityRepository {
    
}
