<?php

namespace LogicBundle\Repository;

/**
 * TratamientoAlimentacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TratamientoAlimentacionRepository extends \Doctrine\ORM\EntityRepository
{
}
