<?php

namespace LogicBundle\Repository;

/**
 * TratamientoHojaEvolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TratamientoHojaEvolucionRepository extends \Doctrine\ORM\EntityRepository
{
}
