<?php

namespace LogicBundle\Repository;

/**
 * UnidadDeportivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadDeportivaRepository extends \Doctrine\ORM\EntityRepository
{
}
