<?php

namespace LogicBundle\Repository;

/**
 * UsuarioDivisionReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioDivisionReservaRepository extends \Doctrine\ORM\EntityRepository {

    public function buscarAsistentesReserva($reserva) {
         $em = $this->getEntityManager();
        
        return $em->getRepository('ApplicationSonataUserBundle:User')
                ->createQueryBuilder("u")
                ->join("u.divisionReservas", "udr")
                ->join("udr.divisionReserva", "r")
                ->where("r.reserva = :reserva")
                ->setParameter("reserva", $reserva)->getQuery()->getResult();
    }

}
