<?php

namespace LogicBundle\Repository;

/**
 * UsuarioOrganizacionDeportivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioOrganizacionDeportivaRepository extends \Doctrine\ORM\EntityRepository
{
}
