<?php

namespace LogicBundle\Repository;

/**
 * ValoracionInicialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoracionInicialRepository extends \Doctrine\ORM\EntityRepository
{
}
