<?php

namespace LogicBundle\Repository;

/**
 * ValoracionAlimentariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoracionAlimentariaRepository extends \Doctrine\ORM\EntityRepository
{
}
