<?php

namespace LogicBundle\Repository;

/**
 * ValoracionAlimentacionFactorExternoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoracionAlimentacionFactorExternoRepository extends \Doctrine\ORM\EntityRepository
{
}
