<?php

namespace LogicBundle\Repository;

/**
 * VinculateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VinculateRepository extends \Doctrine\ORM\EntityRepository
{
}
