<?php

namespace LogicBundle\Repository;

/**
 * VistaBannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VistaBannerRepository extends \Doctrine\ORM\EntityRepository {
    
}
