ito_oauth_server_auth_login:
    path: /oauth/v2/auth_login
    defaults: { _controller: ITOOAuthServerBundle:Security:login }
    
ito_oauth_server_auth_login_check:
    path: /oauth/v2/auth_login_check
    defaults: { _controller: ITOOAuthServerBundle:Security:loginCheck }
