services:
    ito_aouth.tokens.action_listener:
        class: ITO\OAuthServerBundle\EventListener\ClientRequestListener
        tags: 
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: ["@service_container"]
    
    ito_aouth.token.validate.action_listener:
        class: ITO\OAuthServerBundle\EventListener\TokenRequestListener
        tags: 
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: ["@service_container"]
