services:
#    itoapi.example:
#        class: ITO\APIBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ito.tools.response.builder:
        class: ServicesBundle\Tools\ResponseBuilder
        arguments: ["@doctrine.orm.default_entity_manager", "@request_stack"]